# Generated by Django 2.2.1 on 2019-10-21 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('posts', '0006_auto_20191020_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='post',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='userprofile.UserProfile'),
        ),
    ]
