# Generated by Django 2.2.1 on 2019-10-13 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('nationality', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('SA', 'South Africa'), ('UG', 'Uganda')], default='none', max_length=50)),
                ('profession', models.CharField(default='none', max_length=100)),
                ('Addres', models.CharField(default='none', max_length=400)),
                ('profile_pic', models.ImageField(default='none', upload_to='profile_picture')),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
