# Generated by Django 2.2.1 on 2019-10-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Addres',
            new_name='Address',
        ),
    ]
