# Generated by Django 2.2.1 on 2019-10-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20191021_0849'),
        ('accounts', '0004_auto_20191020_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
