# Generated by Django 2.2.1 on 2019-10-21 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('SA', 'South Africa'), ('UG', 'Uganda')], max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=400)),
                ('profile_pic', models.ImageField(blank=True, upload_to='images/profile_picture')),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
